FROM python:3.10-alpine

WORKDIR /consumer

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8081

CMD ["python", "app.py", "&", "python", "consume_app.py"]