FROM python:3.10-alpine

WORKDIR /consumer

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x docker-consumer-entrypoint.sh

EXPOSE 8081

CMD ["./docker-consumer-entrypoint.sh"]
