version: "3.9"
services:
  aiohttp-server:
    build:
      context: .
      dockerfile: Dockerfile.aiohttp
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - rabbitmq

  consumer:
    build:
      context: .
      dockerfile: Dockerfile.consumer
    ports:
      - "8081:8081"
    depends_on:
      - rabbitmq
      - aiohttp-server

  postgres:
    hostname: db
    restart: always
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: zhanat
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: demo
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    hostname: rabbit
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"  # RabbitMQ messaging port
      - "15672:15672"  # RabbitMQ management UI port
    environment:
      RABBITMQ_DEFAULT_USER: zhanat
      RABBITMQ_DEFAULT_PASS: zhanat

volumes:
  postgres_data:
