"""add extension type for image

Revision ID: 219961dd06bf
Revises: fec64331e7f6
Create Date: 2023-07-25 22:33:17.920330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219961dd06bf'
down_revision = 'fec64331e7f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image', sa.Column('extension_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'extension_type')
    # ### end Alembic commands ###
